#! /bin/bash

# Generate Readme
function main() {
    if [[ $# -eq 1 && "$1" == "init" ]]; then
        [[ ! -d markdown ]] && mkdir markdown && cd markdown

        init
    elif [[ -f main.md ]]; then
        generate_readme
    elif [[ -d markdown ]]; then
        echo "dir: markdown/ found"

        if [[ -f markdown/main.md ]]; then
            cd markdown
            echo "file: markdown/main.md found"

            generate_readme
        else
            echo "file: markdown/main.md not found"
            init
        fi
    else
        echo "usage: type \`readme init\` to initialize a markdown directory"
    fi
}


# Generate Readme
function generate_readme() {
    bash ../scripts/mdcompile

    if [[ -f compiled.md ]]; then
        mv compiled.md ../README.md

        echo "Succesfully compiled markdown and generated README"
    else
        echo "error: compiling failed"
    fi

    cd
}


# Initialize markdown dir
function init() {
    echo "Initializing markdown directory..."

    touch markdown/main.md
    mkdir markdown/sections

    echo "Done"
}

main "$@"
