name: Auto-update Pre-commit
run-name: Updating Pre-commit Configuration on ${{ github.repository }}

on:
  schedule:
    - cron: 0 0 * * 0 # Run every Sunday at midnight UTC
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning

jobs:
  auto_update:
    name: Perform auto-update of pre-commit configuration
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.5.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v3.5.3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v4.7.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install and upgrade PIP
        run: python -m pip install --upgrade pip

      - name: Install Pre-commit
        run: pip install pre-commit

      - name: Update pre-commit
        run: pre-commit autoupdate

      - name: Create PR
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v5.0.2
        with:
          token: ${{ secrets.SEYLUBOT_PAT }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          delete-branch: true
